module.exports = {
  GOOGLE_API_CREDENTIALS: {},
  PREFIX: "!",
  DISCORD_TOKEN: "",
  ENABLE_DB: false,
  SHEET_PRIVATE_ID: "",
  MOD_SHEET_PRIVATE_ID: "",
  GLOBAL_SHEET_PRIVATE_ID: "",
  NAMES_SHEET_PRIVATE_ID: "",
  SENTRY_DSN: "",
  ENABLE_SENTRY: false,
  OWNER: "",
};
